/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");

module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    colors: {
      white: "#FFFFFF",
      black: "#000000",
      "dark-gray": "#424245",
      gray: "#808080",
      "light-gray": "#D2D2D7",
      "extra-light": "#F5F5F7",
      "black-brightness": "#121212E6",
      blur: "#D2D2D759",
      error: "#F55F56",
      success: "#32936F",
      "mindful-gray-10": "#F7F4F2",
      "mindful-gray-20": "#E8DDD9",
      "mindful-gray-30": "#D5C2B9",
      "mindful-gray-40": "#BDA193",
      "mindful-gray-50": "#AC836C",
      "mindful-gray-60": "#926247",
      "mindful-gray-70": "#6D4B36",
      "mindful-gray-80": "#4B3425",
      "mindful-gray-90": "#332419",
      "mindful-gray-100": "#1F160F",
      "mindful-gray-100/32": "#1F160F52",
      "mindful-gray-100/48": "#1F160F7A",
      "mindful-gray-100/64": "#1F160FA3",
      "serenity-green-10": "#F7F8F2",
      "serenity-green-20": "#E5EAD7",
      "serenity-green-30": "#CFD9B5",
      "serenity-green-40": "#B4C48D",
      "serenity-green-50": "#9BB068",
      "serenity-green-60": "#7D944D",
      "serenity-green-70": "#5A6B38",
      "serenity-green-80": "#3D4A26",
      "serenity-green-90": "#29321A",
      "serenity-green-100": "#191E10",
      "empathy-orange-10": "#FFF0EB",
      "empathy-orange-20": "#FFD2C2",
      "empathy-orange-30": "#FEAF8F",
      "empathy-orange-40": "#FE814B",
      "empathy-orange-50": "#FE631B",
      "empathy-orange-60": "#DF4B01",
      "empathy-orange-70": "#A23901",
      "empathy-orange-80": "#702901",
      "empathy-orange-90": "#4C1D00",
      "empathy-orange-100": "#2E1200",
      "zen-yellow-10": "#FFF8EB",
      "zen-yellow-20": "#FFEBC2",
      "zen-yellow-30": "#FFDB8F",
      "zen-yellow-40": "#FFCE5C",
      "zen-yellow-50": "#FFBD1A",
      "zen-yellow-60": "#E0A500",
      "zen-yellow-70": "#A37A00",
      "zen-yellow-80": "#705600",
      "zen-yellow-90": "#4D3C00",
      "zen-yellow-100": "#2E2500",
      "gentle-violet-10": "#FBEBFF",
      "gentle-violet-20": "#F4C2FF",
      "gentle-violet-30": "#EC8FFF",
      "gentle-violet-40": "#E552FF",
      "gentle-violet-50": "#CE30E8",
      "gentle-violet-60": "#B516CA",
      "gentle-violet-70": "#861093",
      "gentle-violet-80": "#670070",
      "gentle-violet-90": "#47004D",
      "gentle-violet-100": "#2C002E",
    },
    fontSize: {
      xs: ["12px", "normal"],
      sm: ["14px", "normal"],
      md: ["16px", "normal"],
      lg: ["18px", "normal"],
      xl: ["20px", "normal"],
      "2xl": ["24px", "normal"],
    },
    extend: {},
  },
  plugins: [
    plugin(function ({ addComponents }) {
      const labels = {
        ".label-xs": {
          fontSize: "10px",
          fontWeight: "800",
          letterSpacing: "10%",
          lineHeight: "normal",
        },
        ".label-sm": {
          fontSize: "12px",
          fontWeight: "800",
          letterSpacing: "10%",
          lineHeight: "normal",
        },
        ".label-md": {
          fontSize: "14px",
          fontWeight: "800",
          letterSpacing: "10%",
          lineHeight: "normal",
        },
        ".label-lg": {
          fontSize: "16px",
          fontWeight: "800",
          letterSpacing: "10%",
          lineHeight: "normal",
        },
        ".label-xl": {
          fontSize: "18px",
          fontWeight: "800",
          letterSpacing: "10%",
          lineHeight: "normal",
        },
        ".label-2xl": {
          fontSize: "20px",
          fontWeight: "800",
          letterSpacing: "10%",
          lineHeight: "normal",
        },
      };
      const paragraph = {
        ".paragraph-xs": {
          fontSize: "12px",
          fontWeight: "500",
          letterSpacing: "-1%",
          lineHeight: "160%",
        },
        ".paragraph-sm": {
          fontSize: "14px",
          fontWeight: "500",
          letterSpacing: "-1%",
          lineHeight: "160%",
        },
        ".paragraph-md": {
          fontSize: "16px",
          fontWeight: "500",
          letterSpacing: "-1%",
          lineHeight: "160%",
        },
        ".paragraph-lg": {
          fontSize: "18px",
          fontWeight: "500",
          letterSpacing: "-1%",
          lineHeight: "160%",
        },
        ".paragraph-xl": {
          fontSize: "20px",
          fontWeight: "500",
          letterSpacing: "-1%",
          lineHeight: "160%",
        },
        ".paragraph-2xl": {
          fontSize: "24px",
          fontWeight: "500",
          letterSpacing: "-1%",
          lineHeight: "160%",
        },
      };
      const heading = {
        ".heading-xs-medium": {
          fontSize: "24px",
          fontWeight: "500",
          letterSpacing: "-2%",
          lineHeight: "32px",
        },
        ".heading-xs-semibold": {
          fontSize: "24px",
          fontWeight: "600",
          letterSpacing: "-2%",
          lineHeight: "32px",
        },
        ".heading-xs-bold": {
          fontSize: "24px",
          fontWeight: "700",
          letterSpacing: "-2%",
          lineHeight: "32px",
        },
        ".heading-sm-medium": {
          fontSize: "24px",
          fontWeight: "500",
          letterSpacing: "-2%",
          lineHeight: "38px",
        },
        ".heading-sm-semibold": {
          fontSize: "24px",
          fontWeight: "600",
          letterSpacing: "-2%",
          lineHeight: "38px",
        },
        ".heading-sm-bold": {
          fontSize: "24px",
          fontWeight: "700",
          letterSpacing: "-2%",
          lineHeight: "38px",
        },
        ".heading-md-medium": {
          fontSize: "36px",
          fontWeight: "500",
          letterSpacing: "-2%",
          lineHeight: "44px",
        },
        ".heading-md-semibold": {
          fontSize: "36px",
          fontWeight: "600",
          letterSpacing: "-2%",
          lineHeight: "44px",
        },
        ".heading-md-bold": {
          fontSize: "36px",
          fontWeight: "700",
          letterSpacing: "-2%",
          lineHeight: "44px",
        },
        ".heading-lg-medium": {
          fontSize: "48px",
          fontWeight: "500",
          letterSpacing: "-2%",
          lineHeight: "56px",
        },
        ".heading-lg-semibold": {
          fontSize: "48px",
          fontWeight: "600",
          letterSpacing: "-2%",
          lineHeight: "56px",
        },
        ".heading-lg-bold": {
          fontSize: "48px",
          fontWeight: "700",
          letterSpacing: "-2%",
          lineHeight: "56px",
        },
        ".heading-xl-medium": {
          fontSize: "60px",
          fontWeight: "500",
          letterSpacing: "-2%",
          lineHeight: "68px",
        },
        ".heading-xl-semibold": {
          fontSize: "60px",
          fontWeight: "600",
          letterSpacing: "-2%",
          lineHeight: "68px",
        },
        ".heading-xl-bold": {
          fontSize: "60px",
          fontWeight: "700",
          letterSpacing: "-2%",
          lineHeight: "68px",
        },
        ".heading-2xl-medium": {
          fontSize: "72px",
          fontWeight: "500",
          letterSpacing: "-2%",
          lineHeight: "80px",
        },
        ".heading-2xl-semibold": {
          fontSize: "72px",
          fontWeight: "600",
          letterSpacing: "-2%",
          lineHeight: "80px",
        },
        ".heading-2xl-bold": {
          fontSize: "72px",
          fontWeight: "700",
          letterSpacing: "-2%",
          lineHeight: "80px",
        },
      };
      const display = {
        ".display-sm-semibold": {
          fontSize: "96px",
          fontWeight: "600",
          letterSpacing: "-2%",
          lineHeight: "100px",
        },
        ".display-sm-bold": {
          fontSize: "96px",
          fontWeight: "700",
          letterSpacing: "-2%",
          lineHeight: "100px",
        },
        ".display-md-semibold": {
          fontSize: "128px",
          fontWeight: "600",
          letterSpacing: "-2%",
          lineHeight: "100px",
        },
        ".display-md-bold": {
          fontSize: "128px",
          fontWeight: "700",
          letterSpacing: "-2%",
          lineHeight: "100px",
        },
        ".display-lg-semibold": {
          fontSize: "180px",
          fontWeight: "600",
          letterSpacing: "-2%",
          lineHeight: "100px",
        },
        ".display-lg-bold": {
          fontSize: "180px",
          fontWeight: "700",
          letterSpacing: "-2%",
          lineHeight: "100px",
        },
      };
      addComponents({
        ...labels,
        ...paragraph,
        ...heading,
        ...display,
      });
    }),
  ],
};
